### ISSUE TITLE
An odd question about Moonpod Game's data archive, especially in the game Starscape

### ISSUE THREAD

**Issue by 3x3y3z3t** [ToxicFrog/archive#1]
Hi. I'm using your moonpak tool to unpack the game Starscape's binary. I worked perfectly (thank you a lot). Despite the re-pack function is incomplete, I've managed to be able to modify the archive directly using hex editor with the help of your tool (to see how data is stored).
What I want to ask is: how can you know the structure of the archive? I mean, do you perform disassembly on the executable, or examine the archive itself (pretty much the former I think)? Please feel free to email me at recette.lemongrass95@gmail.com. Thanks.

P/S: the explain: I'm planning to make a small modification for the game. What I'm doing is try to add more items to the game. And it seems that the game don't accept any newly added item. It still load the archive, crash if it can't find an "original" item, and seems to ignore every other things not intended.

**Comment by ToxicFrog** [comment]
It's been 10+ years since I wrote this, but as best I can remember, I did it entirely by looking at the archive, no disassembly of the exe. The format is pretty straightforward; if you open it in a hex editor almost the first thing you see is a filename, and once you know how the filenames are structured it's easy to look for more of them and pick out common patterns.

Looking at the executable would probably have let me figure out more of it, like what that almost-a-zip-file at the end is for, but in the end I didn't need that. (I don't remember _what_ I needed it for, honestly.)

Sorry I can't be more help.
